#!/usr/bin/ruby -w
require 'socket'
require 'optparse'

module NervePlay
  # Console-ready exception
  SettingsError = Class.new(RuntimeError)

  class Settings
    def initialize(args)
      @mode = nil
      @file = nil

      op = OptionParser.new
      words = op.parse(args)
      command = words[0] || cli_fail("no command_given")
      others = words[1..-1]

      #lolhax
      cp = OptionParser.new
      cp.on("--queue") { @mode = :queue }
      cp.on("--daemon-stop") { @mode = :quit }
      cp.parse(["--#{command}"])

      if queue?
        @file = others[0] || cli_fail("file is required")

        fail if others.length > 1
      end
    end

    def file; @file; end

    def quit?; @mode == :quit; end
    def queue?; @mode == :queue; end

    def cli_fail(msg)
      raise SettingsError, msg
    end
  end

  class CommandLine
    def initialize(argv)
      @argv = argv
    end

    # Output exception info and do the exit codes.
    def run!
      run_errorless
    end

    # Don't handle exceptions
    def run_errorless
      @settings = Settings.new(@argv)
      socket = UNIXSocket.new("/tmp/nerve.socket")

      if @settings.quit?
        socket.write("MADAGASCAR\n")
      elsif @settings.queue?
        socket.write("QUEUE #{@settings.file}\n")
      else
        fail "no command set"
      end
    end
  end
end

NervePlay::CommandLine.new(ARGV).run!
