#ifndef NERVE_CONFIG_HPP
#define NERVE_CONFIG_HPP

#cmakedefine NERVE_VERSION "@NERVE_VERSION@"
#cmakedefine NERVE_HOST_SYSTEM "@NERVE_HOST_SYSTEM@"
#cmakedefine NERVE_TARGET_SYSTEM "@NERVE_TARGET_SYSTEM@"

#endif
