.TH "nerved" "1" "Feb 19 2009" "" "User Manuals"
.SH NAME
.LP
.B
nerved \- nerve audio player daemon
.SH SYNOPSIS
.LP
\fBnerved\fR \fI[OPTION]\fR...
.SH DESCRIPTION
.LP
\fBNerved\fR holds the playlist state and performs the audio processing 
operations.  It is controlled using an IPC interface.
.SH
.SH "SEE ALSO"
.LP
\fBnerve(1)\fR
.SH AUTHOR
.LP
James Webber
.SH COPYRIGHT
.LP
Copyright (C) 2008-9 under the GNU Lesser GPL, version 3.
